// packages/vue/src/QirtaasEditor.vue
<script setup lang="ts">
// Thin Vue adapter over @qirtaas/core's imperative mount() API: mount on insert,
// destroy on teardown, and forward the few live-updatable props to the editor's
// setters. Everything else is mount-time config. Vue is a peerDependency — this
// wrapper shares the host's Vue (core is bundled with Vue externalized).
import { ref, onMounted, onBeforeUnmount, watch } from "vue";
import { createQirtaasClient } from "@qirtaas/core";
import type {
  EditorInstance,
  EditorMountOptions,
  QirtaasClientOptions,
  Json,
  Locale,
  Theme,
  BookThemePreset,
  PageMode,
  SaveState,
  ErrorCode,
} from "@qirtaas/core";

const props = defineProps<{
  apiUrl?: string;
  documentId?: string;
  initialContent?: Json | null;
  getToken: NonNullable<QirtaasClientOptions["getToken"]>;
  locale?: Locale;
  theme?: Theme;
  pageMode?: PageMode;
  bookHeader?: EditorMountOptions["bookHeader"];
  bookTheme?: BookThemePreset;
  readOnly?: boolean;
  autofocus?: boolean;
  autosave?: EditorMountOptions["autosave"];
  extensions?: EditorMountOptions["extensions"];
  keymap?: EditorMountOptions["keymap"];
  abbreviations?: EditorMountOptions["abbreviations"];
}>();

const emit = defineEmits<{
  ready: [];
  change: [json: Json];
  saveStateChange: [state: SaveState];
  documentCreated: [id: string];
  error: [code: ErrorCode, detail?: unknown];
  tokenExpired: [];
  event: [name: string, props?: Record<string, unknown>];
}>();

const host = ref<HTMLElement | null>(null);
let instance: EditorInstance | null = null;

onMounted(() => {
  if (!host.value) return;
  const client = createQirtaasClient({ apiUrl: props.apiUrl, getToken: props.getToken });
  instance = client.mountEditor(host.value, {
    documentId: props.documentId,
    initialContent: props.initialContent ?? null,
    locale: props.locale,
    theme: props.theme,
    pageMode: props.pageMode,
    bookHeader: props.bookHeader,
    bookTheme: props.bookTheme,
    readOnly: props.readOnly,
    autofocus: props.autofocus,
    autosave: props.autosave,
    extensions: props.extensions,
    keymap: props.keymap,
    abbreviations: props.abbreviations,
    onReady: () => emit("ready"),
    onChange: (json) => emit("change", json),
    onSaveStateChange: (state) => emit("saveStateChange", state),
    onDocumentCreated: (id) => emit("documentCreated", id),
    onError: (code, detail) => emit("error", code, detail),
    onTokenExpired: () => emit("tokenExpired"),
    onEvent: (name, eventProps) => emit("event", name, eventProps),
  });
});

// Only theme + editable change after mount; the rest require a remount.
watch(
  () => props.theme,
  (theme) => {
    if (theme) instance?.setTheme(theme);
  }
);
watch(
  () => props.bookTheme,
  (theme) => instance?.setBookTheme(theme ?? "classical-monochrome")
);
watch(
  () => props.readOnly,
  (readOnly) => instance?.setEditable(!readOnly)
);

onBeforeUnmount(() => {
  instance?.destroy();
  instance = null;
});

defineExpose({
  getJSON: () => instance?.getJSON() ?? null,
  getHTML: () => instance?.getHTML() ?? "",
  save: () => instance?.save() ?? Promise.resolve(),
  setEditable: (editable: boolean) => instance?.setEditable(editable),
  setTheme: (theme: Theme) => instance?.setTheme(theme),
  setBookTheme: (theme: BookThemePreset) => instance?.setBookTheme(theme),
});
</script>

<template>
  <!-- The editor owns an internal scroll view (pinned toolbar, scrolling body),
       so it fills its container. The host must give this element a bounded
       height (e.g. a sized dialog body or `h-[60vh]`). -->
  <div ref="host" style="height: 100%"></div>
</template>

// packages/react/src/QirtaasEditor.ts
// React adapter over @qirtaas/core's mount() API. React only drives the
// wrapper's lifecycle; the editor itself is a self-contained Vue island that
// core bundles in (a React host needs no Vue). Written with createElement (no
// JSX) so the package builds without a JSX transform.
import {
  createElement,
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
} from "react";
import { createQirtaasClient } from "@qirtaas/core";
import type {
  EditorInstance,
  EditorMountOptions,
  QirtaasClientOptions,
  Json,
  Locale,
  Theme,
  BookThemePreset,
  SaveState,
  ErrorCode,
} from "@qirtaas/core";

export interface QirtaasEditorProps {
  apiUrl?: string;
  documentId?: string;
  initialContent?: Json | null;
  getToken: NonNullable<QirtaasClientOptions["getToken"]>;
  locale?: Locale;
  theme?: Theme;
  pageMode?: EditorMountOptions["pageMode"];
  bookHeader?: EditorMountOptions["bookHeader"];
  bookTheme?: BookThemePreset;
  readOnly?: boolean;
  autofocus?: boolean;
  autosave?: EditorMountOptions["autosave"];
  extensions?: EditorMountOptions["extensions"];
  keymap?: EditorMountOptions["keymap"];
  abbreviations?: EditorMountOptions["abbreviations"];
  onReady?: () => void;
  onChange?: (json: Json) => void;
  onSaveStateChange?: (state: SaveState) => void;
  onDocumentCreated?: (id: string) => void;
  onError?: (code: ErrorCode, detail?: unknown) => void;
  onTokenExpired?: () => void;
  onEvent?: (name: string, props?: Record<string, unknown>) => void;
}

export interface QirtaasEditorHandle {
  getJSON: () => Json | null;
  getHTML: () => string;
  save: () => Promise<void>;
  setEditable: (editable: boolean) => void;
  setTheme: (theme: Theme) => void;
  setBookTheme: (theme: BookThemePreset) => void;
}

export const QirtaasEditor = forwardRef<QirtaasEditorHandle, QirtaasEditorProps>(
  function QirtaasEditor(props, ref) {
    const host = useRef<HTMLDivElement>(null);
    const instance = useRef<EditorInstance | null>(null);
    // Latest props for the callbacks, so mount can stay a once-only effect while
    // still calling the current handlers.
    const latest = useRef(props);
    latest.current = props;

    // Mount once. StrictMode double-invokes this (mount → cleanup → mount); the
    // cleanup's destroy() fully tears down, so the second mount is clean.
    useEffect(() => {
      if (!host.current) return;
      const p = latest.current;
      const client = createQirtaasClient({ apiUrl: p.apiUrl, getToken: p.getToken });
      const inst = client.mountEditor(host.current, {
        documentId: p.documentId,
        initialContent: p.initialContent ?? null,
        locale: p.locale,
        theme: p.theme,
        pageMode: p.pageMode,
        bookHeader: p.bookHeader,
        bookTheme: p.bookTheme,
        readOnly: p.readOnly,
        autofocus: p.autofocus,
        autosave: p.autosave,
        extensions: p.extensions,
        keymap: p.keymap,
        abbreviations: p.abbreviations,
        onReady: () => latest.current.onReady?.(),
        onChange: (json) => latest.current.onChange?.(json),
        onSaveStateChange: (state) => latest.current.onSaveStateChange?.(state),
        onDocumentCreated: (id) => latest.current.onDocumentCreated?.(id),
        onError: (code, detail) => latest.current.onError?.(code, detail),
        onTokenExpired: () => latest.current.onTokenExpired?.(),
        onEvent: (name, eventProps) => latest.current.onEvent?.(name, eventProps),
      });
      instance.current = inst;
      return () => {
        inst.destroy();
        instance.current = null;
      };
    }, []);

    // Live-updatable props → imperative setters.
    useEffect(() => {
      if (props.theme) instance.current?.setTheme(props.theme);
    }, [props.theme]);
    useEffect(() => {
      instance.current?.setBookTheme(props.bookTheme ?? "classical-monochrome");
    }, [props.bookTheme]);
    useEffect(() => {
      instance.current?.setEditable(!props.readOnly);
    }, [props.readOnly]);

    useImperativeHandle(
      ref,
      () => ({
        getJSON: () => instance.current?.getJSON() ?? null,
        getHTML: () => instance.current?.getHTML() ?? "",
        save: () => instance.current?.save() ?? Promise.resolve(),
        setEditable: (editable: boolean) => instance.current?.setEditable(editable),
        setTheme: (theme: Theme) => instance.current?.setTheme(theme),
        setBookTheme: (theme: BookThemePreset) =>
          instance.current?.setBookTheme(theme),
      }),
      []
    );

    // The editor owns an internal scroll view (pinned toolbar, scrolling body),
    // so it fills its container; the host must give it a bounded height.
    return createElement("div", { ref: host, style: { height: "100%" } });
  }
);
